logging.file.name: logs/purple_microlab.log
logging.pattern.console: "%d %-5level %logger : %msg%n"
logging.pattern.file: "%d %-5level [%thread] %logger : %msg%n"
logging.level.: INFO

server:
  port: 9039
  session-timeout: 6000
  connection-timeout: 120000
  servlet:
    context-path: /sts


spring.datasource.url: jdbc:mysql://localhost:3367/sts_test?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username: admin
spring.datasource.password: PFOxx2314b
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.testOnBorrow: true
spring.datasource.validationQuery: SELECT 1





spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql: false
spring.jpa.hibernate.ddl-auto: update
spring.jpa.generate-ddl: true
spring.jpa.properties.hibernate.cache.use_second_level_cache: false
spring.jpa.properties.hibernate.cache.use_query_cache: false
spring.jpa.properties.hibernate.cache.use_structured_entries: false
spring.jpa.properties.hibernate.cache.use_minimal_puts: false
spring.jpa.properties.hibernate.cache.generate_statistics: false

spring.jackson.serialization.fail-on-empty-beans: false

spring.thymeleaf.enabled : true
spring.thymeleaf.cache: true
